Create zad2.html
Szczenathemonke/javascriptWebowoZadania3 pull request #2
Opened 2022-06-14 11:12 UTC by Szczenathemonke

2022-06-14 11:38 UTC, Killavus commented on zad2.html
> +    <style>
Style warto wyciągnąć do osobnego pliku i zalinkować za pomocą elementu `link`.

2022-06-14 11:39 UTC, Killavus commented on zad2.html
> +    <img class="null" id="Szczena" src="https://djabolo.niezniszczalny-chinczyk.com/assets/gowno/smiechostki.png">
Co to za `class`?

2022-06-14 13:11 UTC, Killavus commented on zad2.html
> +            if(counter === 3){
Może warto zrobić funkcję `updateButtonState` przyjmującą parametr `counter`? Jest wtedy o wiele mniej ifów:

```
function updateButtonState(counter) {
  const inc = document.getElementById("btnIncrease");
  const dec = document.getElementById("btnDecrease");

  inc.disabled = counter >= 3;
  dec.disabled = counter < 1;
}
```

2022-06-14 13:13 UTC, Killavus requested changes
Działa. Rozbij rozwiązanie na mniejsze funkcje. To jest bardziej i bardziej ważne im większy kod będziesz miał do ogarnięcia.

2022-06-15 09:23 UTC, Szczenathemonke commented on zad2.html
> +    <img class="null" id="Szczena" src="https://djabolo.niezniszczalny-chinczyk.com/assets/gowno/smiechostki.png">
wyjściowy `class` żeby pozniej ta lista `class`  z obrotami działała, wcześniej robiłem tak że dodawałem klase z obrotami i usuwałem jak znowu było 0deg ale tak wyglądało mi lepiej, jeżeli mam to zmienić to myślałem żeby albo:
-wrócić do dodawania usuwania klasy
-albo zrobić `class` rotate0 który nie daje `transform` obrazka

2022-06-15 09:23 UTC, Szczenathemonke commented on zad2.html
> +    <style>
done

2022-06-15 09:47 UTC, Szczenathemonke commented on zad2.html
> +            if(counter === 3){
done

2022-06-15 09:51 UTC, Szczenathemonke commented on zad2.html
> +            img1.className = classList[counter];
nie wiem czy dobrze to zrozumiałem ale dodałem taką funkcję która zawiera zmiane `class`

2022-06-15 12:47 UTC, Killavus commented on zad2.html
> +    <img class="null" id="Szczena" src="https://djabolo.niezniszczalny-chinczyk.com/assets/gowno/smiechostki.png">
Jest git, zrozumiałem jak to działa. Odrobinę brzydko bo zostawiasz taką dziwną wartość, ale obleci.

2022-06-15 12:48 UTC, Killavus approved these changes
Bardzo dobra robota! Jak Ci się podoba taki kod? Z jednej strony jest mniej czytelny bo musisz 'skakać' między definicjami funkcji, z drugiej strony bardziej czytelny bo nazwałeś sobie te 'części' i dopóki one działają to nawet nie musisz patrzeć co się dzieje w środku tych funkcji.

2022-06-20 07:00 UTC, merged