Create zad3.html
Szczenathemonke/javascriptWebowoZadania3 pull request #3
Opened 2022-06-14 11:13 UTC by Szczenathemonke

2022-06-14 13:14 UTC, Killavus commented on zad3.html
> +            if(img1.style.transform === "rotate(270deg)"){
Powinno iść do 350 stopni a nie do 270.

2022-06-14 13:16 UTC, Killavus commented on zad3.html
> +            img1.style.transform = 'rotate('+counter+'deg)';
Jest też inna opcja na tworzenie łańcuchów znaków ze zmiennymi w środku, tzw. template string literal syntax:

```
img1.style.transform = `rotate(${counter}deg)`;
```

W ten sposób unikasz łączenia za pomocą `+`.

2022-06-14 13:18 UTC, Killavus requested changes
Poprawki z zadania nr 2 aplikują się i tutaj - spróbuj korzystać z większej ilości funkcji. Staraj się myśleć w kategoriach "logicznych mniejszych części" - każda logiczna mniejsza część powinna być funkcją. Jeżeli wykonujesz to samo, ale dla dwóch elementów to może wystarczy funkcja z parametrem jaki to element. I tak dalej.

2022-06-14 13:20 UTC, Killavus commented on zad3.html
> +            counter += 10
Tutaj warto wprowadzić sobie jakąś stałą typu `const COUNTER_ROTATION_STEP = 10` i użyć jej zamiast `10`. Ogólnie korzystanie z takich wartości 'z dupy' nazywa się _magic numbers_ i [jest odradzane](https://en.wikipedia.org/wiki/Magic_number_(programming)#Accepted_uses).

2022-06-15 12:49 UTC, Killavus commented on zad3.html
> +            img1.style.transition ="transform 0.5s";
To dalej wstaw do jakiejś klasy w CSS którą będzie miał ten element. Możesz nawet to zawrzeć w idku "Szczena":

```
#szczena {
  transition: transform 0.5s;
}
```

2022-06-15 12:50 UTC, Killavus approved these changes
Dobra robota! Warto statyczne style wrzucić do CSS - tam one należą bardziej niż w JSie.

2022-06-20 07:06 UTC, Szczenathemonke commented
przerzuciłem ten jeden element `style ` do pliku css -> `transition: transform 0.5s; `

2022-06-20 07:06 UTC, merged